version: "2"

linters-settings:
  disable:
    - typecheck
  depguard:
    list-type: allowlist
    include-go-root: true
    packages:
      - main:
          - "github.com/divir112/otus_hw/internal/**"
          - "github.com/ilyakaznacheev/cleanenv"
          - "github.com/jackc/pgx/v4/pgxpool"
          - "github.com/georgysavva/scany/pgxscan"
          - "github.com/jackc/pgx/**"
      - test:
          - "github.com/divir112/otus_hw/internal/**"